# Generated by Django 5.2.7 on 2025-10-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='存放位置')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('unit', models.CharField(max_length=20, verbose_name='单位')),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='批号')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='采购日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='有效期至')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
            ],
            options={
                'verbose_name': '库存条目',
                'verbose_name_plural': '库存条目',
                'ordering': ['chemical__name_cn', 'location'],
            },
        ),
    ]
