# Generated by Django 5.2.7 on 2025-10-25 07:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('cas_no', models.CharField(max_length=50, unique=True)),
                ('molecular_formula', models.CharField(blank=True, max_length=100, null=True)),
                ('molecular_weight', models.CharField(blank=True, max_length=100, null=True)),
                ('aliases', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('specification', models.CharField(blank=True, max_length=255, null=True)),
                ('form_state', models.CharField(blank=True, max_length=50, null=True)),
                ('hazard_classes', models.TextField(blank=True, null=True)),
                ('hazard_description', models.TextField(blank=True, null=True)),
                ('signal_word', models.CharField(blank=True, max_length=50, null=True)),
                ('hazard_statements', models.TextField(blank=True, null=True)),
                ('precautionary_statements', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
